<?php

namespace AppBundle\Repository;

use AppBundle\Entity\BlogPost;

/**
 * BlogCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCommentRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * @param BlogPost $post
   * @param int $page
   * @param int $limit
   * @return array
   */
  public function getPostComments(BlogPost $post, $page = 1, $limit = 10)
  {
    $entityManager = $this->getEntityManager();
    $queryBuilder = $entityManager->createQueryBuilder();
    $queryBuilder
      ->select('bc')
      ->from('AppBundle:BlogComment', 'bc')
      ->where('bc.draft = 0 and bc.post =:post')
      ->setParameter('post', $post->getId())
      ->orderBy('bc.id', 'DESC')
      ->setFirstResult($limit * ($page - 1))
      ->setMaxResults($limit);

    return $queryBuilder->getQuery()->getResult();
  }
}
